- README.md
- up & going/ch1.md
> Up&Going/Ch1/###ExecutingAProgram

- up & going/ch1.md
> Up&Going/ch1/##Blocks

- up & going/ch1.md
> Up&Going/Ch1/##Variables

- up & going/ch1.md
> Up&Going/Ch1/##CodeComments

- up & going/ch1.md
> Up&Going/Ch1/##Values&Types##ConvertingBetweenTypes

- up & going/ch1.md
> [Done]Up&Going/Ch1/##Conditionals

- up & going/ch1.md
> [Done]UpAndGoing/Ch1/##Loops

- up & going/ch1.md
> Restore Ch1.md examples from spanish to english

- up & going/ch1.md
> [Done]Up&Going/Ch1/##Practice

- up & going/ch1.md
> [Done]Up&Going/Ch1/##Functions

- up & going/ch1.md
@mballeng91 I've created a new branch with the changes. Please review.
> [Done]pr/up&going/ch1/###scope

- up & going/ch1.md
This PR is intended to make corrections and suggestions to the Chapter 1 that is almost finished.
> [Done]pr/up&going/ch1/review

- up & going/ch2.md
PR for Chapter 2: Into JavaScript
> [InProgress]pr/up&going/ch2/###intojs

- README.md
> Solving issues

- types & grammar/ch1.md
> Primera párrafo

- up & going/ch3.md
> (Done)pr/up&going/ch3/#IntoYDKJS

- up & going/ch2.md
> [Done]: Up and going/ch2/arrays

- up & going/ch2.md
Empecé la Introducción y voy hasta objects
> [DONE]upandgoing/ch2/#valuesandtypes/##objects

- up & going/ch2.md
> [Done]up&going/ch2/####functions

- scope & closures/ch1.md
Hope I can get this to 'done' in 2 or 3 weeks, will depend on how much free time i've got.
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)**.
> [Done]scope&closures/ch1/whatIsScope/#CompilerTheory

- up & going/ch2.md
> [Done]up&going/ch2/###built-in-type-mehods

- README.md
> [DONE]pr/improvements-over-readme

- up & going/ch1.md
- up & going/ch3.md
- Some minor fixes on Ch 3: Dentro de YDKJS
- Fix typo in Ch 1
> [DONE]pr/up&going/ch3/###scope&closures

- async & performance/ch1.md
Done.
@mballeng91 
@EstebanMarin
> [DONE]async-and-performance/ch1/#asynchrony/##event-loop

- .gitignore
- async & performance/ch1.md
@mballeng91 @EstebanMarin Favor revisar.
Esta parte sigue inmediatamente después de https://github.com/You-Dont-Know-JS-ES/Traduccion/pull/56
> [DONE]async-and-performance/ch1/#asynchrony/##a-program-in-chunks

- up & going/ch3.md
> [DONE]pr/up&going/ch3/###this&objectprototypes

- up & going/ch3.md
> [DONE]pr/up&going/ch3/###types&grammar

- README.md
> Adding to README.md

- package.json
> Adding All contributors

- types & grammar/ch1.md
Is this the correct workflow???
**Yes, I promise I've read the [Contributions Guidelines but this is my first contribution and I'm not sure](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).
Ya note mi error en  _types_, lo corregiré mas adelante!
> [Done]pr/types_&_gramar/ch1/#A-type-by-any-other-name
